- name: Add devops user on worker nodes
  hosts: all
  become: yes
  tasks:
    - name: Create devops user
      user:
        name: devops
        shell: /bin/bash
        groups: sudo
        append: yes
        create_home: yes

    - name: Allow devops user to run sudo without password
      lineinfile:
        path: /etc/sudoers
        line: "devops ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"
