- name: Configure Kubernetes Worker Node
  hosts: worker_nodes
  become: true
  connection: ssh

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Kubernetes components
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Disable swap
      command: swapoff -a

    - name: Reset kubeadm (if needed)
      command: kubeadm reset -f
      ignore_errors: yes

    - name: Join Worker Node to Cluster
      command: "{{ kubeadm_join_command }}"
      args:
        creates: /etc/kubernetes/kubelet.conf

