- name: Configure Ansible Worker Node
  hosts: worker
  become: true
  tasks:
    - name: Create Ansible User
      user:
        name: ubuntu
        shell: /bin/bash
        groups: sudo

    - name: Copy SSH Key for Ansible User
      authorized_key:
        user: ubuntu
        key: "{{ lookup('file', '/home/ubuntu/.ssh/id_rsa.pub') }}"
        state: present
