- name: Install Kubernetes on all nodes
  hosts: all
  become: yes
  tasks:
    - name: Update system
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common
        state: present

    - name: Add Kubernetes repo
      shell: echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list

    - name: Install Kubernetes & Docker
      apt:
        name:
          - kubeadm
          - kubelet
          - kubectl
          - docker.io
        state: present

    - name: Enable & start Docker
      service:
        name: docker
        state: started
        enabled: yes
